default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: localhost

development:
  <<: *default
  database: demo_scan_qr_dev

test:
  <<: *default
  database: demo_scan_qr_test

production:
  <<: *default
  database: demo_scan_qr_prod
